#server port
server:
  port: 8090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///kalababa
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      
      
  mvc:
    view:
      prefix: /WEB-INF/page/
      suffix: .jsp
      
logging:
  file: E://mylog.log
  level:
    root: info
    com.kalababa: debug

    